dev: &dev
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: newpassword
  pool: 5
  timeout: 5000

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *dev
  database: sample_development

production:
  <<: *dev
  database: sample_development
